// Generated by gencpp from file mav_utils_msgs/BBoxes.msg
// DO NOT EDIT!


#ifndef MAV_UTILS_MSGS_MESSAGE_BBOXES_H
#define MAV_UTILS_MSGS_MESSAGE_BBOXES_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <mav_utils_msgs/BBox.h>

namespace mav_utils_msgs
{
template <class ContainerAllocator>
struct BBoxes_
{
  typedef BBoxes_<ContainerAllocator> Type;

  BBoxes_()
    : stamp()
    , imageID(0)
    , objects()  {
    }
  BBoxes_(const ContainerAllocator& _alloc)
    : stamp()
    , imageID(0)
    , objects(_alloc)  {
  (void)_alloc;
    }



   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int32_t _imageID_type;
  _imageID_type imageID;

   typedef std::vector< ::mav_utils_msgs::BBox_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mav_utils_msgs::BBox_<ContainerAllocator> >> _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::mav_utils_msgs::BBoxes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_utils_msgs::BBoxes_<ContainerAllocator> const> ConstPtr;

}; // struct BBoxes_

typedef ::mav_utils_msgs::BBoxes_<std::allocator<void> > BBoxes;

typedef boost::shared_ptr< ::mav_utils_msgs::BBoxes > BBoxesPtr;
typedef boost::shared_ptr< ::mav_utils_msgs::BBoxes const> BBoxesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_utils_msgs::BBoxes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_utils_msgs::BBoxes_<ContainerAllocator1> & lhs, const ::mav_utils_msgs::BBoxes_<ContainerAllocator2> & rhs)
{
  return lhs.stamp == rhs.stamp &&
    lhs.imageID == rhs.imageID &&
    lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_utils_msgs::BBoxes_<ContainerAllocator1> & lhs, const ::mav_utils_msgs::BBoxes_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_utils_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_utils_msgs::BBoxes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_utils_msgs::BBoxes_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_utils_msgs::BBoxes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "132eb21f59342318bc09c3939b6621fb";
  }

  static const char* value(const ::mav_utils_msgs::BBoxes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x132eb21f59342318ULL;
  static const uint64_t static_value2 = 0xbc09c3939b6621fbULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_utils_msgs/BBoxes";
  }

  static const char* value(const ::mav_utils_msgs::BBoxes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "time stamp\n"
"int32 imageID\n"
"BBox[] objects\n"
"\n"
"================================================================================\n"
"MSG: mav_utils_msgs/BBox\n"
"int32 boxID\n"
"int32 pixSize\n"
"int32 contourSize\n"
"string colour\n"
"float32 diagIndex\n"
"float32 areaIndex\n"
"float32 eigenIndex\n"
"int32[] rangeX\n"
"int32[] rangeY\n"
"float32[] centre\n"
"float32[] cornerX\n"
"float32[] cornerY\n"
"float32[] eigenVal\n"
"float32[] eigenVec\n"
"int32[] contourX\n"
"int32[] contourY\n"
"bool full\n"
"bool store\n"
;
  }

  static const char* value(const ::mav_utils_msgs::BBoxes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.stamp);
      stream.next(m.imageID);
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BBoxes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_utils_msgs::BBoxes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_utils_msgs::BBoxes_<ContainerAllocator>& v)
  {
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "imageID: ";
    Printer<int32_t>::stream(s, indent + "  ", v.imageID);
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mav_utils_msgs::BBox_<ContainerAllocator> >::stream(s, indent + "    ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_UTILS_MSGS_MESSAGE_BBOXES_H
