// Generated by gencpp from file mav_utils_msgs/RouterData.msg
// DO NOT EDIT!


#ifndef MAV_UTILS_MSGS_MESSAGE_ROUTERDATA_H
#define MAV_UTILS_MSGS_MESSAGE_ROUTERDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace mav_utils_msgs
{
template <class ContainerAllocator>
struct RouterData_
{
  typedef RouterData_<ContainerAllocator> Type;

  RouterData_()
    : id(0)
    , position()  {
    }
  RouterData_(const ContainerAllocator& _alloc)
    : id(0)
    , position(_alloc)  {
  (void)_alloc;
    }



   typedef int16_t _id_type;
  _id_type id;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;





  typedef boost::shared_ptr< ::mav_utils_msgs::RouterData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_utils_msgs::RouterData_<ContainerAllocator> const> ConstPtr;

}; // struct RouterData_

typedef ::mav_utils_msgs::RouterData_<std::allocator<void> > RouterData;

typedef boost::shared_ptr< ::mav_utils_msgs::RouterData > RouterDataPtr;
typedef boost::shared_ptr< ::mav_utils_msgs::RouterData const> RouterDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_utils_msgs::RouterData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_utils_msgs::RouterData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_utils_msgs::RouterData_<ContainerAllocator1> & lhs, const ::mav_utils_msgs::RouterData_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.position == rhs.position;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_utils_msgs::RouterData_<ContainerAllocator1> & lhs, const ::mav_utils_msgs::RouterData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_utils_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_utils_msgs::RouterData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_utils_msgs::RouterData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_utils_msgs::RouterData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b89d964391b2067f851638625d693b3";
  }

  static const char* value(const ::mav_utils_msgs::RouterData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b89d964391b2067ULL;
  static const uint64_t static_value2 = 0xf851638625d693b3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_utils_msgs/RouterData";
  }

  static const char* value(const ::mav_utils_msgs::RouterData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 id\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mav_utils_msgs::RouterData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.position);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RouterData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_utils_msgs::RouterData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_utils_msgs::RouterData_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_UTILS_MSGS_MESSAGE_ROUTERDATA_H
