// Generated by gencpp from file mav_utils_msgs/RouterInfo.msg
// DO NOT EDIT!


#ifndef MAV_UTILS_MSGS_MESSAGE_ROUTERINFO_H
#define MAV_UTILS_MSGS_MESSAGE_ROUTERINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <mav_utils_msgs/RouterData.h>

namespace mav_utils_msgs
{
template <class ContainerAllocator>
struct RouterInfo_
{
  typedef RouterInfo_<ContainerAllocator> Type;

  RouterInfo_()
    : header()
    , object_id()
    , router_data()  {
    }
  RouterInfo_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object_id(_alloc)
    , router_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<int16_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int16_t>> _object_id_type;
  _object_id_type object_id;

   typedef std::vector< ::mav_utils_msgs::RouterData_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::mav_utils_msgs::RouterData_<ContainerAllocator> >> _router_data_type;
  _router_data_type router_data;





  typedef boost::shared_ptr< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> const> ConstPtr;

}; // struct RouterInfo_

typedef ::mav_utils_msgs::RouterInfo_<std::allocator<void> > RouterInfo;

typedef boost::shared_ptr< ::mav_utils_msgs::RouterInfo > RouterInfoPtr;
typedef boost::shared_ptr< ::mav_utils_msgs::RouterInfo const> RouterInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_utils_msgs::RouterInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_utils_msgs::RouterInfo_<ContainerAllocator1> & lhs, const ::mav_utils_msgs::RouterInfo_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.object_id == rhs.object_id &&
    lhs.router_data == rhs.router_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_utils_msgs::RouterInfo_<ContainerAllocator1> & lhs, const ::mav_utils_msgs::RouterInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_utils_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ff2a8e53da5af51cb59d4d23d6612c0";
  }

  static const char* value(const ::mav_utils_msgs::RouterInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ff2a8e53da5af51ULL;
  static const uint64_t static_value2 = 0xcb59d4d23d6612c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_utils_msgs/RouterInfo";
  }

  static const char* value(const ::mav_utils_msgs::RouterInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"int16[] object_id\n"
"RouterData[] router_data\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: mav_utils_msgs/RouterData\n"
"int16 id\n"
"geometry_msgs/Point position\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::mav_utils_msgs::RouterInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object_id);
      stream.next(m.router_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RouterInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_utils_msgs::RouterInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_utils_msgs::RouterInfo_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object_id[]" << std::endl;
    for (size_t i = 0; i < v.object_id.size(); ++i)
    {
      s << indent << "  object_id[" << i << "]: ";
      Printer<int16_t>::stream(s, indent + "  ", v.object_id[i]);
    }
    s << indent << "router_data[]" << std::endl;
    for (size_t i = 0; i < v.router_data.size(); ++i)
    {
      s << indent << "  router_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::mav_utils_msgs::RouterData_<ContainerAllocator> >::stream(s, indent + "    ", v.router_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_UTILS_MSGS_MESSAGE_ROUTERINFO_H
