// Generated by gencpp from file mav_utils_msgs/signal.msg
// DO NOT EDIT!


#ifndef MAV_UTILS_MSGS_MESSAGE_SIGNAL_H
#define MAV_UTILS_MSGS_MESSAGE_SIGNAL_H

#include <ros/service_traits.h>


#include <mav_utils_msgs/signalRequest.h>
#include <mav_utils_msgs/signalResponse.h>


namespace mav_utils_msgs
{

struct signal
{

typedef signalRequest Request;
typedef signalResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct signal
} // namespace mav_utils_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_utils_msgs::signal > {
  static const char* value()
  {
    return "473669d0643dcd7ad1f24e08b06be56b";
  }

  static const char* value(const ::mav_utils_msgs::signal&) { return value(); }
};

template<>
struct DataType< ::mav_utils_msgs::signal > {
  static const char* value()
  {
    return "mav_utils_msgs/signal";
  }

  static const char* value(const ::mav_utils_msgs::signal&) { return value(); }
};


// service_traits::MD5Sum< ::mav_utils_msgs::signalRequest> should match
// service_traits::MD5Sum< ::mav_utils_msgs::signal >
template<>
struct MD5Sum< ::mav_utils_msgs::signalRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_utils_msgs::signal >::value();
  }
  static const char* value(const ::mav_utils_msgs::signalRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_utils_msgs::signalRequest> should match
// service_traits::DataType< ::mav_utils_msgs::signal >
template<>
struct DataType< ::mav_utils_msgs::signalRequest>
{
  static const char* value()
  {
    return DataType< ::mav_utils_msgs::signal >::value();
  }
  static const char* value(const ::mav_utils_msgs::signalRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_utils_msgs::signalResponse> should match
// service_traits::MD5Sum< ::mav_utils_msgs::signal >
template<>
struct MD5Sum< ::mav_utils_msgs::signalResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_utils_msgs::signal >::value();
  }
  static const char* value(const ::mav_utils_msgs::signalResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_utils_msgs::signalResponse> should match
// service_traits::DataType< ::mav_utils_msgs::signal >
template<>
struct DataType< ::mav_utils_msgs::signalResponse>
{
  static const char* value()
  {
    return DataType< ::mav_utils_msgs::signal >::value();
  }
  static const char* value(const ::mav_utils_msgs::signalResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_UTILS_MSGS_MESSAGE_SIGNAL_H
