// Generated by gencpp from file mav_planning_msgs/ChangeNameService.msg
// DO NOT EDIT!


#ifndef MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICE_H
#define MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICE_H

#include <ros/service_traits.h>


#include <mav_planning_msgs/ChangeNameServiceRequest.h>
#include <mav_planning_msgs/ChangeNameServiceResponse.h>


namespace mav_planning_msgs
{

struct ChangeNameService
{

typedef ChangeNameServiceRequest Request;
typedef ChangeNameServiceResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeNameService
} // namespace mav_planning_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_planning_msgs::ChangeNameService > {
  static const char* value()
  {
    return "d82dc6474dd88dad5e1615ab1b2ca74c";
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameService&) { return value(); }
};

template<>
struct DataType< ::mav_planning_msgs::ChangeNameService > {
  static const char* value()
  {
    return "mav_planning_msgs/ChangeNameService";
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameService&) { return value(); }
};


// service_traits::MD5Sum< ::mav_planning_msgs::ChangeNameServiceRequest> should match
// service_traits::MD5Sum< ::mav_planning_msgs::ChangeNameService >
template<>
struct MD5Sum< ::mav_planning_msgs::ChangeNameServiceRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_planning_msgs::ChangeNameService >::value();
  }
  static const char* value(const ::mav_planning_msgs::ChangeNameServiceRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_planning_msgs::ChangeNameServiceRequest> should match
// service_traits::DataType< ::mav_planning_msgs::ChangeNameService >
template<>
struct DataType< ::mav_planning_msgs::ChangeNameServiceRequest>
{
  static const char* value()
  {
    return DataType< ::mav_planning_msgs::ChangeNameService >::value();
  }
  static const char* value(const ::mav_planning_msgs::ChangeNameServiceRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_planning_msgs::ChangeNameServiceResponse> should match
// service_traits::MD5Sum< ::mav_planning_msgs::ChangeNameService >
template<>
struct MD5Sum< ::mav_planning_msgs::ChangeNameServiceResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_planning_msgs::ChangeNameService >::value();
  }
  static const char* value(const ::mav_planning_msgs::ChangeNameServiceResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_planning_msgs::ChangeNameServiceResponse> should match
// service_traits::DataType< ::mav_planning_msgs::ChangeNameService >
template<>
struct DataType< ::mav_planning_msgs::ChangeNameServiceResponse>
{
  static const char* value()
  {
    return DataType< ::mav_planning_msgs::ChangeNameService >::value();
  }
  static const char* value(const ::mav_planning_msgs::ChangeNameServiceResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICE_H
