// Generated by gencpp from file mav_planning_msgs/ChangeNameServiceResponse.msg
// DO NOT EDIT!


#ifndef MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICERESPONSE_H
#define MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mav_planning_msgs
{
template <class ContainerAllocator>
struct ChangeNameServiceResponse_
{
  typedef ChangeNameServiceResponse_<ContainerAllocator> Type;

  ChangeNameServiceResponse_()
    : success(false)
    , message()  {
    }
  ChangeNameServiceResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeNameServiceResponse_

typedef ::mav_planning_msgs::ChangeNameServiceResponse_<std::allocator<void> > ChangeNameServiceResponse;

typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceResponse > ChangeNameServiceResponsePtr;
typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceResponse const> ChangeNameServiceResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator1> & lhs, const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator1> & lhs, const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_planning_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_planning_msgs/ChangeNameServiceResponse";
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# True on success, false on failure\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeNameServiceResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_planning_msgs::ChangeNameServiceResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICERESPONSE_H
