// Generated by gencpp from file mav_planning_msgs/ChangeNameServiceRequest.msg
// DO NOT EDIT!


#ifndef MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICEREQUEST_H
#define MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mav_planning_msgs
{
template <class ContainerAllocator>
struct ChangeNameServiceRequest_
{
  typedef ChangeNameServiceRequest_<ContainerAllocator> Type;

  ChangeNameServiceRequest_()
    : name()  {
    }
  ChangeNameServiceRequest_(const ContainerAllocator& _alloc)
    : name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;





  typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeNameServiceRequest_

typedef ::mav_planning_msgs::ChangeNameServiceRequest_<std::allocator<void> > ChangeNameServiceRequest;

typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceRequest > ChangeNameServiceRequestPtr;
typedef boost::shared_ptr< ::mav_planning_msgs::ChangeNameServiceRequest const> ChangeNameServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator1> & lhs, const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator1> & lhs, const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace mav_planning_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c1f3d28f1b044c871e6eff2e9fc3c667";
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc1f3d28f1b044c87ULL;
  static const uint64_t static_value2 = 0x1e6eff2e9fc3c667ULL;
};

template<class ContainerAllocator>
struct DataType< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mav_planning_msgs/ChangeNameServiceRequest";
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#request fields\n"
"string name\n"
;
  }

  static const char* value(const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ChangeNameServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mav_planning_msgs::ChangeNameServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAV_PLANNING_MSGS_MESSAGE_CHANGENAMESERVICEREQUEST_H
