(cl:defpackage mav_planning_msgs-srv
  (:use )
  (:export
   "CHANGENAMESERVICE"
   "<CHANGENAMESERVICE-REQUEST>"
   "CHANGENAMESERVICE-REQUEST"
   "<CHANGENAMESERVICE-RESPONSE>"
   "CHANGENAMESERVICE-RESPONSE"
   "PLANNERSERVICE"
   "<PLANNERSERVICE-REQUEST>"
   "PLANNERSERVICE-REQUEST"
   "<PLANNERSERVICE-RESPONSE>"
   "PLANNERSERVICE-RESPONSE"
   "POLYGONSERVICE"
   "<POLYGONSERVICE-REQUEST>"
   "POLYGONSERVICE-REQUEST"
   "<POLYGONSERVICE-RESPONSE>"
   "POLYGONSERVICE-RESPONSE"
  ))

