(cl:in-package mav_utils_msgs-msg)
(cl:export '(BOXID-VAL
          BOXID
          PIXSIZE-VAL
          PIXSIZE
          CONTOURSIZE-VAL
          CONTOURSIZE
          COLOUR-VAL
          COLOUR
          DIAGINDEX-VAL
          DIAGINDEX
          AREAINDEX-VAL
          AREAINDEX
          EIGENINDEX-VAL
          EIGENINDEX
          RANGEX-VAL
          RANGEX
          RANGEY-VAL
          RANGEY
          CENTRE-VAL
          CENTRE
          CORNERX-VAL
          CORNERX
          CORNERY-VAL
          CORNERY
          EIGENVAL-VAL
          EIGENVAL
          EIGENVEC-VAL
          EIGENVEC
          CONTOURX-VAL
          CONTOURX
          CONTOURY-VAL
          CONTOURY
          FULL-VAL
          FULL
          STORE-VAL
          STORE
))