# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from mav_utils_msgs/BBPose.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class BBPose(genpy.Message):
  _md5sum = "e3a05460e544ead82f2d436e3787794c"
  _type = "mav_utils_msgs/BBPose"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 boxID
int32 type
float32 area
bool store
geometry_msgs/Point position

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['boxID','type','area','store','position']
  _slot_types = ['int32','int32','float32','bool','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       boxID,type,area,store,position

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BBPose, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.boxID is None:
        self.boxID = 0
      if self.type is None:
        self.type = 0
      if self.area is None:
        self.area = 0.
      if self.store is None:
        self.store = False
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
    else:
      self.boxID = 0
      self.type = 0
      self.area = 0.
      self.store = False
      self.position = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2ifB3d().pack(_x.boxID, _x.type, _x.area, _x.store, _x.position.x, _x.position.y, _x.position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 37
      (_x.boxID, _x.type, _x.area, _x.store, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_2ifB3d().unpack(str[start:end])
      self.store = bool(self.store)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2ifB3d().pack(_x.boxID, _x.type, _x.area, _x.store, _x.position.x, _x.position.y, _x.position.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 37
      (_x.boxID, _x.type, _x.area, _x.store, _x.position.x, _x.position.y, _x.position.z,) = _get_struct_2ifB3d().unpack(str[start:end])
      self.store = bool(self.store)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2ifB3d = None
def _get_struct_2ifB3d():
    global _struct_2ifB3d
    if _struct_2ifB3d is None:
        _struct_2ifB3d = struct.Struct("<2ifB3d")
    return _struct_2ifB3d
